# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRCEhunTp2lcsfLDdXrXC45KM4cAYdHM

**PASSWORD REMINDER ASSIGNMENT**
"""

my_name = "Ayse"
name = input("Please enter your first name: ").title()

if name == my_name :
    print("Hello, Ayse! The password is : W@12")
else :
    print(f"Hello, {name}! See you later.")